/**
 * POST /api/bug-report
 *
 * Receives a bug report from the dashboard, formats it as a readable
 * markdown file, and saves it to the OpenClaw-Wiki vault at:
 *   Multi-AgentOS/Bug Reports/YYYY-MM-DD-HHMM-{slug}.md
 *
 * Holly (or any agent reading the vault) picks up the file next time she
 * looks at the project. The file is auto-committed to git so it shows
 * up in PRs.
 *
 * Format is designed to be human-readable AND machine-parseable — Holly
 * can grep for "## Severity: critical" or "## Errors" sections.
 */

import { NextRequest } from 'next/server'
import { writeFileSync, mkdirSync, existsSync } from 'fs'
import { execSync } from 'child_process'
import { join } from 'path'

const VAULT_ROOT = '/root/OpenClaw-Wiki'
const PROJECT_DIR = 'Multi-AgentOS'

function slugify(s: string): string {
  return s
    .toLowerCase()
    .slice(0, 60)
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'bug'
}

function nowStamp(): string {
  const d = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}`
}

function severityEmoji(sev: string): string {
  switch (sev) {
    case 'critical': return '🚨'
    case 'data-loss': return '💾'
    case 'broken':   return '🛠️'
    case 'annoyance':return '🔔'
    default:         return '🐛'
  }
}

function renderMarkdown(payload: any): string {
  const c = payload.context || {}
  const errors: any[] = payload.errors || []
  const recent: any[] = payload.recentMessages || []
  const snap = payload.storeSnapshot || {}

  const out: string[] = []
  out.push(`# ${severityEmoji(payload.severity)} Bug report — ${nowStamp()}`)
  out.push('')
  out.push(`**Captured:** ${payload.capturedAt}`)
  out.push(`**Severity:** ${payload.severity}`)
  out.push(`**Source:** ${c.url || 'unknown'}`)
  out.push(`**Agent at time of report:** ${c.activeAgentId || '(none)'}`)
  out.push(`**Model at time of report:** ${c.activeModelId || '(none)'}`)
  out.push(`**Active panel:** ${c.activePanel || '?'}`)
  out.push('')
  out.push('## What happened')
  out.push('')
  out.push(payload.description || '_(no description)_')
  out.push('')
  if (payload.expected) {
    out.push('## What I expected')
    out.push('')
    out.push(payload.expected)
    out.push('')
  }
  out.push('## Environment')
  out.push('')
  out.push(`- **Viewport:** ${c.viewport?.w || '?'}×${c.viewport?.h || '?'}`)
  out.push(`- **Build:** ${c.buildVersion || 'dev'}`)
  out.push(`- **User agent:** ${(c.userAgent || '').slice(0, 200)}`)
  out.push(`- **Vault enabled:** ${c.vaultEnabled ? 'yes' : 'no'}`)
  out.push(`- **Vault SSH user:** ${c.vaultSshUser || '(none — local mode)'}`)
  out.push(`- **Vault SSH key path:** ${c.vaultSshKeyPath || '(none — local mode)'}`)
  out.push(`- **Vault save status:** ${c.vaultSaveStatus || 'idle'}`)
  out.push(`- **Last save:** ${c.vaultLastSaved || 'never'}`)
  out.push('')
  out.push('## Recent errors (' + errors.length + ')')
  out.push('')
  if (errors.length === 0) {
    out.push('_No errors captured before this report._')
  } else {
    for (const e of errors.slice(-15)) {
      const ts = new Date(e.ts).toISOString()
      out.push(`### ${e.kind || 'error'} @ ${ts}`)
      out.push('')
      out.push('```')
      out.push(e.message || '(no message)')
      if (e.stack) {
        out.push(e.stack.split('\n').slice(0, 8).join('\n'))
      }
      if (e.context && Object.keys(e.context).length) {
        out.push('context: ' + JSON.stringify(e.context))
      }
      out.push('```')
      out.push('')
    }
  }
  out.push('## Recent messages (' + recent.length + ')')
  out.push('')
  if (recent.length === 0) {
    out.push('_No recent chat messages._')
  } else {
    for (const m of recent) {
      const ts = new Date(m.ts).toISOString()
      out.push(`- [${m.agentId}] (${m.role}) ${ts}: ${m.text}`)
    }
  }
  out.push('')
  out.push('## Store snapshot')
  out.push('')
  out.push('| Key | Value |')
  out.push('|---|---|')
  out.push(`| Agents with history | ${(snap.agentMessagesKeys || []).join(', ') || '(none)'} |`)
  out.push(`| Total messages | ${snap.messageCount || 0} |`)
  out.push(`| Goals | ${snap.goalsCount || 0} |`)
  out.push(`| Journal entries | ${snap.journalEntriesCount || 0} |`)
  out.push('')
  out.push('---')
  out.push('')
  out.push('_Generated by Multi-AgentOS bug reporter. Holly: triage this and reply in the conversation._')
  out.push('')
  return out.join('\n')
}

function commitToVault(filepath: string, slug: string) {
  try {
    execSync(
      `cd ${VAULT_ROOT} && git add "${filepath}" && git -c user.email=holly@openclaw.local -c user.name=Holly commit -m "bug: ${slug}" 2>&1`,
      { stdio: 'pipe', timeout: 15000 },
    )
  } catch (e: any) {
    // Don't fail the request if git commit fails — file is still on disk
    console.error('git commit failed:', e?.message?.slice(0, 300))
  }
}

export async function POST(req: NextRequest) {
  let body: any
  try {
    body = await req.json()
  } catch {
    return Response.json({ error: 'invalid json' }, { status: 400 })
  }

  if (!body || typeof body !== 'object') {
    return Response.json({ error: 'expected object body' }, { status: 400 })
  }
  if (!body.description || typeof body.description !== 'string' || body.description.trim().length < 3) {
    return Response.json({ error: 'description is required (min 3 chars)' }, { status: 400 })
  }

  const slug = slugify(body.description)
  const stamp = nowStamp()
  const dir = join(VAULT_ROOT, PROJECT_DIR, 'Bug Reports')
  if (!existsSync(dir)) {
    try {
      mkdirSync(dir, { recursive: true })
    } catch (e: any) {
      return Response.json(
        { error: 'failed to create bug reports dir', detail: e.message },
        { status: 500 },
      )
    }
  }

  const filename = `${stamp}-${slug}.md`
  const filepath = join(dir, filename)
  const markdown = renderMarkdown(body)

  try {
    writeFileSync(filepath, markdown, 'utf8')
  } catch (e: any) {
    return Response.json(
      { error: 'failed to write file', detail: e.message },
      { status: 500 },
    )
  }

  // Best-effort git commit
  commitToVault(filepath.replace(VAULT_ROOT + '/', ''), slug)

  return Response.json({
    success: true,
    file: filepath,
    filename,
    relativePath: `${PROJECT_DIR}/Bug Reports/${filename}`,
  })
}
